version = "26.1.2"
mode = "default"
seed = 0
max_ticks = 1700
strict = true

[replay.camera]
view_distance = 8
fov = 78.0
interpolation = "catmull_rom"

[[replay.camera.keyframes]]
time_ms = 0
position = [-13.5, 30.0, 58.0]
yaw = -138.37
pitch = 22.55
fov = 82.0

[[replay.camera.keyframes]]
time_ms = 1000
position = [-13.5, 30.0, 58.0]
yaw = -138.37
pitch = 22.55

[[replay.camera.keyframes]]
time_ms = 22000
yaw = -152.35
pitch = 22.87

[[replay.camera.keyframes]]
time_ms = 43000
position = [12.5, 31.0, 86.0]
yaw = -172.87
pitch = 23.47
fov = 72.0

[[replay.camera.keyframes]]
time_ms = 64000
yaw = 167.74
pitch = 23.02

[[replay.camera.keyframes]]
time_ms = 85000
position = [40.5, 30.0, 94.0]
yaw = 151.19
pitch = 23.66
fov = 80.0


[source]
path = "../schematics/flying-machine.litematic"
initialization = "raw"

[[actions]]
tick = 20
type = "set_block"
pos = { x = 17, y = 21, z = 29 }
name = "minecraft:stone_button"
properties = { face = "wall", facing = "north", powered = "false" }
