version = "26.1.2"
mode = "default"
seed = 0
max_ticks = 225000
strict = true
skip_oracle = true

[monitor]
skip_ticks = 224999

[replay.camera]
view_distance = 8
position = [275.79, 86.0, 202.74]
yaw = 89.56
pitch = -14.10

[source]
path = "../worlds/CPU_22_08_2025.zip"
initialization = "raw"
region = { min = { x = 9, y = 52, z = -1 }, max = { x = 287, y = 157, z = 397 } }

[[source.pastes]]
path = "../schematics/frostbyte-line-drawing.schem"
origin = { x = 64, y = 152, z = 389 }
rotation = "none"
mirror = "none"
ignore_air = true
paste_entities = false
update = true

[[actions]]
tick = 100
type = "press_button"
pos = { x = 274, y = 88, z = 197 }

[[probes]]
name = "pixel_02_05"
type = "property"
pos = { x = 215, y = 78, z = 176 }
property = "lit"

[[probes]]
name = "pixel_03_05"
type = "property"
pos = { x = 215, y = 78, z = 178 }
property = "lit"

[[probes]]
name = "pixel_04_06"
type = "property"
pos = { x = 215, y = 80, z = 180 }
property = "lit"

[[probes]]
name = "pixel_05_06"
type = "property"
pos = { x = 215, y = 80, z = 182 }
property = "lit"

[[probes]]
name = "pixel_06_07"
type = "property"
pos = { x = 215, y = 82, z = 184 }
property = "lit"

[[probes]]
name = "pixel_07_07"
type = "property"
pos = { x = 215, y = 82, z = 186 }
property = "lit"

[[probes]]
name = "pixel_08_08"
type = "property"
pos = { x = 215, y = 84, z = 188 }
property = "lit"

[[probes]]
name = "pixel_09_08"
type = "property"
pos = { x = 215, y = 84, z = 190 }
property = "lit"

[[probes]]
name = "pixel_10_09"
type = "property"
pos = { x = 215, y = 86, z = 192 }
property = "lit"

[[probes]]
name = "pixel_11_09"
type = "property"
pos = { x = 215, y = 86, z = 194 }
property = "lit"

[[probes]]
name = "pixel_12_10"
type = "property"
pos = { x = 215, y = 88, z = 196 }
property = "lit"

[[probes]]
name = "pixel_13_10"
type = "property"
pos = { x = 215, y = 88, z = 198 }
property = "lit"

[[probes]]
name = "pixel_14_11"
type = "property"
pos = { x = 215, y = 90, z = 200 }
property = "lit"

[[probes]]
name = "pixel_15_11"
type = "property"
pos = { x = 215, y = 90, z = 202 }
property = "lit"

[[probes]]
name = "pixel_16_12"
type = "property"
pos = { x = 215, y = 92, z = 204 }
property = "lit"

[[probes]]
name = "pixel_17_12"
type = "property"
pos = { x = 215, y = 92, z = 206 }
property = "lit"

[[probes]]
name = "pixel_18_13"
type = "property"
pos = { x = 215, y = 94, z = 208 }
property = "lit"

[[probes]]
name = "pixel_19_13"
type = "property"
pos = { x = 215, y = 94, z = 210 }
property = "lit"

[[probes]]
name = "pixel_20_14"
type = "property"
pos = { x = 215, y = 96, z = 212 }
property = "lit"

[[probes]]
name = "pixel_21_14"
type = "property"
pos = { x = 215, y = 96, z = 214 }
property = "lit"

[[probes]]
name = "pixel_22_15"
type = "property"
pos = { x = 215, y = 98, z = 216 }
property = "lit"

[[probes]]
name = "pixel_23_15"
type = "property"
pos = { x = 215, y = 98, z = 218 }
property = "lit"

[[probes]]
name = "pixel_24_16"
type = "property"
pos = { x = 215, y = 100, z = 220 }
property = "lit"

[[probes]]
name = "pixel_25_16"
type = "property"
pos = { x = 215, y = 100, z = 222 }
property = "lit"

[[probes]]
name = "pixel_26_17"
type = "property"
pos = { x = 215, y = 102, z = 224 }
property = "lit"

[[probes]]
name = "pixel_27_17"
type = "property"
pos = { x = 215, y = 102, z = 226 }
property = "lit"

[[probes]]
name = "first_pixel_y78_z177"
type = "property"
pos = { x = 215, y = 78, z = 177 }
property = "lit"

[[probes]]
name = "first_pixel_y79_z176"
type = "property"
pos = { x = 215, y = 79, z = 176 }
property = "lit"

[[probes]]
name = "first_pixel_y79_z177"
type = "property"
pos = { x = 215, y = 79, z = 177 }
property = "lit"

[[probes]]
name = "last_pixel_y102_z227"
type = "property"
pos = { x = 215, y = 102, z = 227 }
property = "lit"

[[probes]]
name = "last_pixel_y103_z226"
type = "property"
pos = { x = 215, y = 103, z = 226 }
property = "lit"

[[probes]]
name = "last_pixel_y103_z227"
type = "property"
pos = { x = 215, y = 103, z = 227 }
property = "lit"

[[probes]]
name = "empty_top_right"
type = "property"
pos = { x = 215, y = 78, z = 227 }
property = "lit"

[[probes]]
name = "empty_bottom_left"
type = "property"
pos = { x = 215, y = 103, z = 176 }
property = "lit"

[[probes]]
name = "empty_below_first_run"
type = "property"
pos = { x = 215, y = 80, z = 176 }
property = "lit"

[[probes]]
name = "empty_above_last_run"
type = "property"
pos = { x = 215, y = 101, z = 226 }
property = "lit"

[[expectations]]
tick = 225000
probe = "pixel_02_05"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_03_05"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_04_06"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_05_06"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_06_07"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_07_07"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_08_08"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_09_08"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_10_09"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_11_09"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_12_10"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_13_10"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_14_11"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_15_11"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_16_12"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_17_12"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_18_13"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_19_13"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_20_14"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_21_14"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_22_15"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_23_15"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_24_16"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_25_16"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_26_17"
equals = "true"

[[expectations]]
tick = 225000
probe = "pixel_27_17"
equals = "true"

[[expectations]]
tick = 225000
probe = "first_pixel_y78_z177"
equals = "true"

[[expectations]]
tick = 225000
probe = "first_pixel_y79_z176"
equals = "true"

[[expectations]]
tick = 225000
probe = "first_pixel_y79_z177"
equals = "true"

[[expectations]]
tick = 225000
probe = "last_pixel_y102_z227"
equals = "true"

[[expectations]]
tick = 225000
probe = "last_pixel_y103_z226"
equals = "true"

[[expectations]]
tick = 225000
probe = "last_pixel_y103_z227"
equals = "true"

[[expectations]]
tick = 225000
probe = "empty_top_right"
equals = "false"

[[expectations]]
tick = 225000
probe = "empty_bottom_left"
equals = "false"

[[expectations]]
tick = 225000
probe = "empty_below_first_run"
equals = "false"

[[expectations]]
tick = 225000
probe = "empty_above_last_run"
equals = "false"
