[package]
name = "redstone-java-26"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
autotests = false

[dependencies]
indexmap.workspace = true
redstone-core = { path = "../redstone-core" }
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tracing.workspace = true

[build-dependencies]
serde_json.workspace = true

[dev-dependencies]
redstone-io = { path = "../redstone-io" }

[[test]]
name = "suite"
path = "tests/suite.rs"
