[package]
name = "redstone-render-26"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
glam.workspace = true
redstone-core = { path = "../redstone-core" }
redstone-java-26 = { path = "../redstone-java-26" }
redstone-replay-26 = { path = "../redstone-replay-26" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
wgpu.workspace = true
zip.workspace = true
