use std::borrow::Cow;
use std::io::{BufWriter, Write};

use thiserror::Error;

use crate::{GameTick, ProbeValue, TraceEvent, TraceKind};

const TRACE_BUFFER_CAPACITY: usize = 64 * 1024;

#[derive(Clone, Debug, Default)]
pub struct TraceLog<'a> {
    events: Cow<'a, [TraceEvent]>,
}

impl TraceLog<'static> {
    pub fn new(events: Vec<TraceEvent>) -> Self {
        Self {
            events: Cow::Owned(events),
        }
    }
}

impl<'a> TraceLog<'a> {
    pub fn borrowed(events: &'a [TraceEvent]) -> Self {
        Self {
            events: Cow::Borrowed(events),
        }
    }

    pub fn events(&self) -> &[TraceEvent] {
        &self.events
    }

    pub fn into_events(self) -> Vec<TraceEvent> {
        self.events.into_owned()
    }

    pub fn write_jsonl(&self, output: impl Write) -> Result<(), TraceError> {
        let mut output = BufWriter::with_capacity(TRACE_BUFFER_CAPACITY, output);
        for event in self.events.iter() {
            serde_json::to_writer(&mut output, event)?;
            output.write_all(b"\n")?;
        }
        output.flush()?;
        Ok(())
    }

    pub fn write_vcd(&self, output: impl Write) -> Result<(), TraceError> {
        let mut output = BufWriter::with_capacity(TRACE_BUFFER_CAPACITY, output);
        let mut probes = Vec::<(String, u8)>::new();
        for event in self.events.iter() {
            if let TraceKind::ProbeSample { sample } = &event.kind {
                let width = probe_width(&sample.value);
                if let Some((_, current_width)) =
                    probes.iter_mut().find(|(name, _)| name == &sample.name)
                {
                    *current_width = (*current_width).max(width);
                } else {
                    probes.push((sample.name.clone(), width));
                }
            }
        }

        writeln!(output, "$date generated by redstone-rs $end")?;
        writeln!(output, "$version redstone-rs 0.1 $end")?;
        writeln!(output, "$timescale 1ns $end")?;
        writeln!(output, "$scope module redstone $end")?;
        for (index, (name, width)) in probes.iter().enumerate() {
            writeln!(output, "$var wire {width} p{index} {name} $end")?;
        }
        writeln!(output, "$upscope $end")?;
        writeln!(output, "$enddefinitions $end")?;

        let mut current_tick = None;
        for event in self.events.iter() {
            let TraceKind::ProbeSample { sample } = &event.kind else {
                continue;
            };
            if current_tick != Some(event.tick) {
                current_tick = Some(event.tick);
                writeln!(output, "#{}", event.tick.0)?;
            }
            let Some((index, (_, width))) = probes
                .iter()
                .enumerate()
                .find(|(_, (name, _))| name == &sample.name)
            else {
                continue;
            };
            match &sample.value {
                ProbeValue::Bool(value) => {
                    write_boolean(&mut output, index, *width, *value)?;
                }
                ProbeValue::Integer(value) => {
                    writeln!(output, "b{:064b} p{index}", *value as u64)?;
                }
                ProbeValue::State(value) => {
                    writeln!(output, "b{:064b} p{index}", value.0 as u64)?;
                }
                ProbeValue::String(value) if value == "true" || value == "false" => {
                    writeln!(output, "{}", boolean_vcd(index, *width, value == "true"))?
                }
                ProbeValue::String(value) => match value.parse::<i64>() {
                    Ok(value) => writeln!(output, "b{:064b} p{index}", value as u64)?,
                    Err(_) => writeln!(output, "bx p{index}")?,
                },
                ProbeValue::None if *width == 1 => writeln!(output, "xp{index}")?,
                ProbeValue::None => writeln!(output, "bx p{index}")?,
            }
        }
        if current_tick.is_none() {
            writeln!(output, "#{}", GameTick(0).0)?;
        }
        output.flush()?;
        Ok(())
    }
}

fn write_boolean(
    output: &mut impl Write,
    index: usize,
    width: u8,
    value: bool,
) -> Result<(), std::io::Error> {
    writeln!(output, "{}", boolean_vcd(index, width, value))
}

fn boolean_vcd(index: usize, width: u8, value: bool) -> String {
    if width == 1 {
        format!("{}p{index}", if value { '1' } else { '0' })
    } else {
        format!("b{:064b} p{index}", u64::from(value))
    }
}

fn probe_width(value: &ProbeValue) -> u8 {
    match value {
        ProbeValue::Bool(_) => 1,
        ProbeValue::String(value) if value == "true" || value == "false" => 1,
        _ => 64,
    }
}

#[derive(Debug, Error)]
pub enum TraceError {
    #[error(transparent)]
    Io(#[from] std::io::Error),
    #[error(transparent)]
    Json(#[from] serde_json::Error),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{BlockPos, MicroStep, Probe, ProbeSample, SimulationPhase};

    #[test]
    fn vcd_encodes_boolean_and_numeric_property_strings() {
        let events = [("powered", "true"), ("power", "15"), ("facing", "north")]
            .into_iter()
            .enumerate()
            .map(|(index, (name, value))| TraceEvent {
                tick: GameTick(1),
                micro_step: MicroStep(index as u64 + 1),
                phase: SimulationPhase::PostTick,
                kind: TraceKind::ProbeSample {
                    sample: ProbeSample {
                        name: name.to_owned(),
                        probe: Probe::Property {
                            pos: BlockPos::ZERO,
                            property: name.to_owned(),
                        },
                        value: ProbeValue::String(value.to_owned()),
                    },
                },
            })
            .collect::<Vec<_>>();
        let mut output = Vec::new();
        TraceLog::new(events).write_vcd(&mut output).unwrap();
        let output = String::from_utf8(output).unwrap();

        assert!(output.contains("$var wire 1 p0 powered $end"));
        assert!(output.contains("$var wire 64 p1 power $end"));
        assert!(output.contains("1p0"));
        assert!(
            output.contains("b0000000000000000000000000000000000000000000000000000000000001111 p1")
        );
        assert!(output.contains("bx p2"));
    }

    #[test]
    fn vcd_uses_a_vector_when_a_probe_changes_from_none_to_boolean() {
        let probe = Probe::Property {
            pos: BlockPos::ZERO,
            property: "powered".to_owned(),
        };
        let events = [ProbeValue::None, ProbeValue::String("true".to_owned())]
            .into_iter()
            .enumerate()
            .map(|(index, value)| TraceEvent {
                tick: GameTick(index as u64 + 1),
                micro_step: MicroStep(1),
                phase: SimulationPhase::PostTick,
                kind: TraceKind::ProbeSample {
                    sample: ProbeSample {
                        name: "powered".to_owned(),
                        probe: probe.clone(),
                        value,
                    },
                },
            })
            .collect::<Vec<_>>();
        let mut output = Vec::new();
        TraceLog::new(events).write_vcd(&mut output).unwrap();
        let output = String::from_utf8(output).unwrap();

        assert!(output.contains("$var wire 64 p0 powered $end"));
        assert!(output.contains("bx p0"));
        assert!(
            output.contains("b0000000000000000000000000000000000000000000000000000000000000001 p0")
        );
    }
}
